# Generated by Django 2.1.3 on 2019-01-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlcloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='train',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mlcloud.Tag'),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
